services:
  - type: web
    name: proyecto-mercado-viva
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT --log-level debug
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://proyecto-mercado-viva.onrender.com
